name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: "JDK ${{ matrix.java }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 16 ] # [ 17-ea, 16, 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Download JDK'
        id: download-jdk
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.java }}
      - name: 'Set up JDK, Project ${{ matrix.project }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.download-jdk.outputs.version }}
          jdkFile: "${{ steps.download-jdk.outputs.file }}"
      - name: 'Print Java version'
        run: java -version
      - name: 'Build with Maven'
        run: mvn --batch-mode --no-transfer-progress verify
