name: Quality_Outreach

on: workflow_dispatch

jobs:

  build:

    name: Quality Outreach Java ${{ matrix.java-version }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [14, 15, 16]

    runs-on: ${{ matrix.os }}

    env:
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Download Java version ${{ matrix.java-version }}
        uses: sormuras/download-jdk@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Quality Outreach with Java ${{ matrix.java-version }}
        run: mvn verify

  projects:
  
    name: Quality Outreach Java ${{ matrix.project }}
    
    strategy:
      matrix:
        os: [ ubuntu-latest ] #[ macos-latest, windows-latest ]
        project: [ Loom, Panama, Valhalla ]
          
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Download Java project ${{ matrix.project }}
        uses: sormuras/download-jdk@v1
        id: download-jdk
        with:
          feature: ${{ matrix.project }}
      - name: Quality Outreach with Java ${{ matrix.project }}
        run: mvn verify
